spring:
  datasource:
    url: jdbc:mysql://localhost:3306/head_system
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
  servlet:
    multipart:
      enabled: true

logging:
  level:
    org:
      springframework:
        data: TRACE
        beans: DEBUG